network.host: 0.0.0.0

cluster.name: aozora-bi
discovery.seed_hosts: ['elasticsearch01', 'elasticsearch02', 'elasticsearch03']
cluster.initial_master_nodes: ['elasticsearch01', 'elasticsearch02', 'elasticsearch03']
node.name: ${NODE_NAME}

