version: "3"
services:
  embulk:
    build: ./embulk
    container_name: aozora-bi_embulk
    tty: true

  elasticsearch01:
    build: ./es
    container_name: aozora-bi_elasticsearch01
    volumes:
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es/data/elasticsearch01:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    environment:
      NODE_NAME: elasticsearch01

  elasticsearch02:
    build: ./es
    container_name: aozora-bi_elasticsearch02
    volumes:
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es/data/elasticsearch02:/usr/share/elasticsearch/data
    ports:
      - 9202:9200
    environment:
      NODE_NAME: elasticsearch02

  elasticsearch03:
    build: ./es
    container_name: aozora-bi_elasticsearch03
    volumes:
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es/data/elasticsearch03:/usr/share/elasticsearch/data
    ports:
      - 9203:9200
    environment:
      NODE_NAME: elasticsearch03
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    container_name: aozora-bi_kibana
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    links:
      - elasticsearch01:elasticsearch
    ports:
      - 5601:5601
